'use client';
import React from 'react'
import { Metadata } from 'next'
import { usePathname } from 'next/navigation'

const MetaData = () => {
  const pathname = usePathname();
  const metadata: Metadata = {
    title: pathname === '/' ? 'Home Page' : pathname.replace('/', '').charAt(0).toUpperCase() + pathname.slice(2),
    description: "Generated by create next app",
    keywords: "next.js,react,typescript",
  };
  return (
    <>
      <div>
        {metadata.title && (
          <title>{String(metadata.title)}</title>
        )}
      </div>
    </>
  );
}

export default MetaData;
